### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Matsu-pt** [Matsu-pt/protospace-35063#1]
https://protospace-35063.herokuapp.com/

**Comment by takumi0530** [comment]
@Matsu-pt さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
- [x] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること**

現状、ログアウト状態でプロトタイプの画像、プロトタイプ名をクリックすると、詳細ページではなく、エラーページに遷移してしまいます。
<img width="733" alt="スクリーンショット 2021-04-05 16 12 06" src="https://user-images.githubusercontent.com/76197191/113548148-0022b700-962a-11eb-9610-0e89e274e0ab.png">

- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
現状、エラーページに遷移してしまいます。
<img width="733" alt="スクリーンショット 2021-04-05 16 12 06" src="https://user-images.githubusercontent.com/76197191/113548288-3a8c5400-962a-11eb-81bc-c779185696eb.png">

### **[次回ご提出時に確認させていただきます]**

下記のものは、ログアウト状態で詳細画面に遷移できなかったため、次回ご提出時に確認させていただきます。

- [ ] ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること
- [ ] コメント投稿欄は、ログイン状態のユーザーへのみ、詳細ページに表示されていること
- [ ] ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されていること

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@Matsu-pt さん、再度のご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について修正が確認できませんでした。
マージやデプロイ忘れの可能性もございます。今一度ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できるよう修正しましょう**
- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するよう修正しましょう**
- [ ] **ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されるよう修正しましょう**
現状、ログアウト状態のユーザーはトップページ・プロトタイプ詳細ページ・ユーザー詳細ページに遷移できず、ログインページにリダイレクトする状態です。

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
現状、プロトタイプ詳細ページの投稿者名をクリックすると、トップページに遷移してしまいます。
<img width="1440" alt="スクリーンショット 2021-04-05 18 07 15" src="https://user-images.githubusercontent.com/54050089/113558689-1422e480-963b-11eb-847c-e25fea139679.png">


- [ ] **コメント機能にて、フォームを空のまま投稿しようとすると、投稿できずにそのページに留まるよう修正しましょう**
現状、コメントを空欄のまま送信するとエラー画面に遷移してしまいます。
<img width="698" alt="スクリーンショット 2021-04-05 16 48 03" src="https://user-images.githubusercontent.com/54050089/113558619-efc70800-963a-11eb-8b15-1dd5401a07df.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@Matsu-pt さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、前回お伝えした一部の項目については修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございますので、以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態のユーザーだけが、投稿ページへ遷移できるよう修正しましょう**
現状、新規投稿ページのURLを直接入力すると、ログアウト状態のユーザーも投稿ページへ遷移できてしまう状態です。

- [x] **コメント機能にて、フォームを空のまま投稿しようとすると、投稿できずにそのページに留まるよう修正しましょう**
現状、コメントを空欄のまま送信するとエラー画面に遷移してしまいます。

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
現状、プロトタイプ詳細ページの投稿者名をクリックすると、トップページに遷移してしまいます。
<img width="1440" alt="スクリーンショット_2021-04-06_11_07_14" src="https://user-images.githubusercontent.com/54050089/113648883-56463780-96c8-11eb-8b0a-6226d9a79839.png">

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされるよう修正しましょう**
現状、以下の状態です。どちらもログインページにリダイレクトされるよう修正しましょう。
・新規投稿ページ　→　遷移できてしまう
・編集ページ　→　トップページに遷移

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
@Matsu-pt さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
